### ISSUE TITLE
Signature verification methods should not panic if they return Result

### ISSUE THREAD

**Issue by wellcaffeinated** [decentralized-identity/did-key.rs#26]
Hey there. I was planning to use this lib for my project but am unable to if signature verification panics on invalid signature data. Since signature content can come from untrusted sources, I need to be able to gracefully handle invalid signature data.

https://docs.rs/did-key/0.1.0/src/did_key/ed25519.rs.html#180-186

The verify method for various keypairs returns a `Result` type, but the signature data uses `.expect()` instead of mapping the error so I can't handle that case.

Thanks!

**Comment by tmarkovski** [comment]
Fixed with #27. Thanks for reporting this
