### ISSUE TITLE
signature_bls is abandoned

### ISSUE THREAD

**Issue by pinkforest** [decentralized-identity/did-key.rs#38]
Re: https://github.com/fission-codes/fission-cli/issues/21#issue-1465054547

I investigated and ockam seems to have dropped support for bls and it looks like they don't have a repository anymore for it either.

In any case this causes dependency duplication with bls12_381_plus and the latest signature_bls only brings ^0.5 whilst did-key brings ^0.7

I also queried with ockam at: https://github.com/build-trust/ockam/issues/3864 to clarify it.

Might need new bls signature crate to use or fork teh ockam one and bring the `bls12_381_plus` up.

**Comment by mrinalwadhwa** [comment]
Hi 👋 from the Ockam team. We're not using bls anymore and didn't realize did:key was using it directly :worried:. If someone would like to maintain it, we'd be happy to help get that started in whatever way we can.

**Comment by pinkforest** [comment]
hmmm.. I could adopt it and keep it at least maintained for others - I'll bring the :crab: chore :robot: with me :)

**Comment by tmarkovski** [comment]
`signature_bls` has been removed in the #35 as it was confusing to use sign with a G1G2 key. I think the entire `CoreSign` trait doesn't belong in the did:key functionality, as the spec itself doesn't really define one.

**Comment by pinkforest** [comment]
Sweet, so shall be waiting a release for that then. Thanks!
